apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels: 
    app: postgres

type: Opaque
data:
  #POSTGRES_DB: bd_escolares
  POSTGRES_DB: YmRfZXNjb2xhcmVz
  #POSTGRES_USER: admin
  POSTGRES_USER: YWRtaW4=
  #POSTGRES_USER: admin
  POSTGRES_PASSWORD: YWRtaW4=